from django.conf import settings

SHOPPING_CART_APP_NAME = getattr(settings, "SHOPPING_CART_APP_NAME", "Shopping Cart")
SHOPPING_CART_ENABLE_MARKETPLACE = getattr(settings, "SHOPPING_CART_ENABLE_MARKETPLACE", True)
SHOPPING_CART_ENABLE_LEADERBOARD = getattr(settings, "SHOPPING_CART_ENABLE_LEADERBOARD", True)
SHOPPING_CART_DISCORD_WEBHOOK_URL = getattr(settings, "SHOPPING_CART_DISCORD_WEBHOOK_URL", "")
SHOPPING_CART_NOTIFY_ON_NEW_REQUEST = getattr(settings, "SHOPPING_CART_NOTIFY_ON_NEW_REQUEST", True)
SHOPPING_CART_NOTIFY_ON_CLAIM = getattr(settings, "SHOPPING_CART_NOTIFY_ON_CLAIM", True)
SHOPPING_CART_FULFILLED_RETENTION_DAYS = getattr(settings, "SHOPPING_CART_FULFILLED_RETENTION_DAYS", 90)
SHOPPING_CART_ABANDONED_CART_DAYS = getattr(settings, "SHOPPING_CART_ABANDONED_CART_DAYS", 30)
SHOPPING_CART_PAGINATION_SIZE = getattr(settings, "SHOPPING_CART_PAGINATION_SIZE", 25)
SHOPPING_CART_DEFAULT_HUBS = getattr(settings, "SHOPPING_CART_DEFAULT_HUBS", ['Jita', 'Amarr', 'Dodixie', 'Rens', 'Hek'])
