name: Code Quality

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

jobs:
  code-quality:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pylint bandit safety
        pip install -e .
    
    - name: Run pylint
      run: |
        pylint shopping_cart/ --rcfile=.pylintrc || true
      continue-on-error: true
    
    - name: Run bandit security check
      run: |
        bandit -r shopping_cart/ -f json -o bandit-report.json || true
      continue-on-error: true
    
    - name: Check dependencies for vulnerabilities
      run: |
        safety check --json || true
      continue-on-error: true
    
    - name: Upload reports
      uses: actions/upload-artifact@v3
      if: always()
      with:
        name: quality-reports
        path: |
          bandit-report.json
